### ISSUE TITLE
Service always changes enable from False to True

### ISSUE THREAD

**Issue by taschik** [thomasvandoren/puppet-redis#21]
For every puppet run the Service/enable is getting changed:

Notice: /Stage[main]/Redis/Redis::Instance[redis-default]/Service[redis-6900]/enable: enable changed 'false' to 'true'

I am running the manifest on a Debian Wheezy using puppet 3.2.2

how can I fix this?

**Comment by jjtorroglosa** [comment]
I was running into the same issue. The init script didn't create the pidfile. In my case, there was another redis instance running on the same port. So, although redis init script failed to start the daemon because of this, it returned 0, and puppet thought that has been started successfully. The next time you run puppet occurs the same: it will say 'changed from stopped to running'. Stopping the old instance fixed it.

Hope it helps.

**Comment by thomasvandoren** [comment]
Archiving this repo and closing all open issues and pull requests. Please fork and maintain any changes in another repo. Sorry for the inconvenience.
